// Terms of Service, Privacy Policy, and a shared site footer.
// These render as their own pages at /terms and /privacy. The backend
// serves index.html for any path, so App.jsx reads window.location.pathname
// and shows the matching page here. Footer links are plain <a href> so they
// work with that same catch-all.

const UPDATED = 'October 1, 2026';

function LegalShell({ title, children }) {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:py-14">
      <a href="/" className="text-sm font-700 text-primary hover:underline">
        ← Back to AuditMyIEP
      </a>
      <h1 className="mt-5 font-heading text-3xl font-800 text-foreground">{title}</h1>
      <p className="mt-1 text-sm text-muted-foreground">Last updated: {UPDATED}</p>
      <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-foreground/90">
        {children}
      </div>
      <div className="mt-12 border-t border-border pt-6">
        <SiteFooter />
      </div>
    </div>
  );
}

function H2({ children }) {
  return <h2 className="font-heading text-xl font-800 text-foreground">{children}</h2>;
}

export function TermsPage() {
  return (
    <LegalShell title="Terms of Service">
      <div className="rounded-2xl border border-good/30 bg-good-bg p-4 text-sm font-600 text-foreground/90">
        AuditMyIEP is an educational tool to help parents understand and prepare for the IEP
        process. It is not legal advice and does not create an attorney-client relationship.
        AuditMyIEP does not replace a special-education attorney or advocate. For legal advice
        about your child's specific situation, consult a licensed attorney in your state.
      </div>

      <div>
        <H2>1. What AuditMyIEP is</H2>
        <p className="mt-2">
          AuditMyIEP ("the Service," "we," "us") is an educational tool that reviews an uploaded
          Individualized Education Program (IEP) against federal special-education standards (the
          Individuals with Disabilities Education Act, 34 CFR Part 300, and the Endrew F. v.
          Douglas County School District standard) and returns a plain-language report to help a
          parent or guardian prepare to advocate for their child.
        </p>
      </div>

      <div>
        <H2>2. Not legal advice</H2>
        <p className="mt-2">
          The Service provides general educational information only. It is not legal advice, does
          not create an attorney-client relationship, and does not guarantee any educational,
          legal, or financial outcome. Laws and timelines vary by state, and the Service may not
          reflect your state's specific rules. Always consult a licensed attorney or qualified
          advocate before making decisions about your child's education or any dispute with a
          school district.
        </p>
      </div>

      <div>
        <H2>3. No guarantee of accuracy</H2>
        <p className="mt-2">
          The report is generated by automated analysis and may contain errors, omissions, or
          interpretations you disagree with. You are responsible for reviewing your IEP and
          verifying any information before acting on it. The Service is provided "as is" and "as
          available," without warranties of any kind, express or implied, including fitness for a
          particular purpose.
        </p>
      </div>

      <div>
        <H2>4. Eligibility</H2>
        <p className="mt-2">
          You must be at least 18 years old and the parent, legal guardian, or an authorized
          representative of the child whose IEP you upload, or otherwise have the legal right to
          upload that document.
        </p>
      </div>

      <div>
        <H2>5. Payment and refunds</H2>
        <p className="mt-2">
          Each audit costs $19, charged at the time of use through our payment processor, Stripe.
          We never see or store your full card details. If the Service fails to deliver a report
          you paid for, you may request a refund within 7 days by emailing help@auditmyiep.com.
        </p>
      </div>

      <div>
        <H2>6. Acceptable use and intellectual property</H2>
        <p className="mt-2">
          AuditMyIEP, including its analysis logic, report format, scoring approach, and branding,
          is the property of AuditMyIEP and is protected by applicable law. You may use the
          Service and your own report for your personal, non-commercial advocacy. You may not
          copy, resell, reverse-engineer, scrape, or build a competing product from the Service,
          or use it to provide paid services to others, without written permission.
        </p>
      </div>

      <div>
        <H2>7. Limitation of liability</H2>
        <p className="mt-2">
          To the fullest extent permitted by law, AuditMyIEP is not liable for any indirect,
          incidental, or consequential damages arising from your use of the Service, and total
          liability for any claim is limited to the amount you paid for the audit giving rise to
          the claim.
        </p>
      </div>

      <div>
        <H2>8. Changes</H2>
        <p className="mt-2">
          We may update these terms at any time. Continued use after a change means you accept the
          updated terms.
        </p>
      </div>

      <div>
        <H2>9. Governing law</H2>
        <p className="mt-2">
          These terms are governed by the laws of the State of Colorado, without regard to
          conflict-of-law rules.
        </p>
      </div>

      <div>
        <H2>10. Contact</H2>
        <p className="mt-2">
          Questions: <a className="text-primary hover:underline" href="mailto:help@auditmyiep.com">help@auditmyiep.com</a>
        </p>
      </div>
    </LegalShell>
  );
}

export function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy">
      <div>
        <H2>What we do with your IEP</H2>
        <p className="mt-2">
          When you upload your IEP, its text is sent to our AI provider (Anthropic / Claude) to
          generate your report, and the report is returned to your screen. Your IEP is held only
          in memory for the few moments the analysis takes. It is never written to disk, never
          saved to a database, and is deleted as soon as your report is delivered. We cannot
          retrieve it later, and neither can anyone else.
        </p>
      </div>

      <div>
        <H2>Not used to train AI</H2>
        <p className="mt-2">
          Your IEP is not used to train any AI model. Under Anthropic's commercial API terms, data
          sent through their API is not used for model training. Anthropic may retain API data
          briefly for security and abuse monitoring under their own terms.
        </p>
      </div>

      <div>
        <H2>Third parties that process data</H2>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Anthropic (Claude) — analyzes your IEP text to produce the report. It is not stored after processing.</li>
          <li>Stripe — processes your payment. We store only a payment confirmation ID, never your card details.</li>
          <li>Resend — sends the email copy of your report and any updates you receive.</li>
        </ul>
      </div>

      <div>
        <H2>What we store</H2>
        <p className="mt-2">
          We store: (1) a Stripe payment confirmation ID (no card data), and (2) your email
          address, which you provide to receive your report. We use your email to deliver your
          report and receipt and to send occasional updates, tips, and offers about AuditMyIEP.
          Nothing about your child or your IEP is kept.
        </p>
      </div>

      <div>
        <H2>Your email choices</H2>
        <p className="mt-2">
          Your report and payment receipt are transactional messages tied to your purchase. In
          addition, we may send you marketing updates about AuditMyIEP. Every marketing email
          includes an unsubscribe link, and you may opt out of marketing messages at any time —
          opting out does not affect transactional messages or your ability to use the Service.
          You can also email help@auditmyiep.com to be removed from marketing.
        </p>
      </div>

      <div>
        <H2>Children's information</H2>
        <p className="mt-2">
          Your IEP may contain information about a child. We process it solely to generate your
          report and delete it immediately afterward. We do not sell or share it, and it is never
          used for advertising or training.
        </p>
      </div>

      <div>
        <H2>Contact</H2>
        <p className="mt-2">
          Privacy questions: <a className="text-primary hover:underline" href="mailto:help@auditmyiep.com">help@auditmyiep.com</a>
        </p>
      </div>
    </LegalShell>
  );
}

export function SiteFooter() {
  return (
    <footer className="no-print mt-10 text-center text-xs leading-relaxed text-muted-foreground">
      <p>
        AuditMyIEP is an educational tool, not legal advice, and does not replace a
        special-education attorney or advocate.
      </p>
      <p className="mt-2">
        <a href="/terms" className="font-600 text-primary hover:underline">Terms of Service</a>
        <span className="mx-2">·</span>
        <a href="/privacy" className="font-600 text-primary hover:underline">Privacy Policy</a>
        <span className="mx-2">·</span>
        <a href="mailto:help@auditmyiep.com" className="font-600 text-primary hover:underline">help@auditmyiep.com</a>
      </p>
      <p className="mt-2">© {new Date().getFullYear()} AuditMyIEP</p>
    </footer>
  );
}
